trigger:
- main

variables:
- group: 'Telegrambot'

pool: $(Agente)

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'docker buildx build --platform linux/amd64,linux/arm64 -t henda24/telegrambot:latest -t henda24/telegrambot:$(Build.BuildId) --push .'

- task: replacetokens@5
  inputs:
    rootDirectory: '$(Build.SourcesDirectory)'
    targetFiles: 'k8s/**.yaml'
    encoding: 'utf-8'
    tokenPattern: 'custom'
    tokenPrefix: '<'
    tokenSuffix: '>'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    actionOnNoFiles: 'continue'
    enableTransforms: false
    enableRecursion: false
    useLegacyPattern: false
    enableTelemetry: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/k8s'
    ArtifactName: 'manifests'
    publishLocation: 'Container'