trigger:
- main

variables:
- group: 'Telegrambot'
- name: IMAGE
  value: 'henda24/telegrambot'

pool: $(Agente)

steps:
- task: Bash@3
  displayName: Building and Pushing Image
  inputs:
    targetType: 'inline'
    script: 'docker buildx build --platform linux/amd64,linux/arm64 -t $(IMAGE):latest -t $(IMAGE):$(Build.BuildId) --push .'

- task: Bash@3
  displayName: Cleaning Images
  inputs:
    targetType: 'inline'
    script: 'docker rmi -f $(IMAGE):latest $(IMAGE):$(Build.BuildId)'

- task: replacetokens@5
  inputs:
    rootDirectory: '$(Build.SourcesDirectory)'
    targetFiles: 'k8s/**.yaml'
    encoding: 'utf-8'
    tokenPattern: 'custom'
    tokenPrefix: '<'
    tokenSuffix: '>'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    actionOnNoFiles: 'continue'
    enableTransforms: false
    enableRecursion: false
    useLegacyPattern: false
    enableTelemetry: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/k8s'
    ArtifactName: 'manifests'
    publishLocation: 'Container'