version: "3"
services:
  telegrambot:
    container_name: telegrambot
    build: .
    # SET TOKEN,INSTA_PASS,INSTA_USER,SESSION_FILE ENV
    env_file:
      - .env
    command: --token $TOKEN
    restart: unless-stopped