[project]
name = "telegrambot"
requires-python = ">=3.12"
version = "0.0.2"
dependencies = [
    "pytelegrambotapi==4.30.0",
    "requests>=2.33.0",
    "lxml>=6.1.0",
    "urllib3>=2.7.0",
]

[tool.uv]
constraint-dependencies = [
    "idna>=3.15",
    "urllib3>=2.7.0",
]
required-environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
    "sys_platform == 'linux' and platform_machine == 'aarch64'",
]