apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegrambot
  labels:
    app: telegrambot
spec:
  selector:
    matchLabels:
      app: telegrambot
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: telegrambot
    spec:
      containers:
        - name: telegrambot
          image: henda24/telegrambot:1715
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          envFrom:
            - secretRef:
                name: telegrambot
          args: ["--token", "$(TOKEN)"]
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
      volumes:
        - name: tz-config
          hostPath:
            path: /etc/localtime
