apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegrambot
  namespace: services
  labels:
    app: telegrambot
spec:
  selector:
    matchLabels:
      app: telegrambot
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: telegrambot
    spec:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
      containers:
        - name: telegrambot
          image: henda24/telegrambot:1671
          resources:
            limits:
              cpu: 1
              memory: 1Gi
          envFrom:
            - secretRef:
                name: telegrambot
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
      volumes:
        - name: tz-config
          hostPath:
            path: /etc/localtime
